trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build Stage'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        #pylint your_django_project/ --fail-under=70
        pwd
        ls
        cd /application
        pylint --load-plugins pylint_django --django-settings-module=core.settings **/*.py
      displayName: 'Setup Virtual Environment and Run pylint'
      continueOnError: true # Continue with the next steps even if pylint fails

    

